name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "akobashikawa@gmail.com"
        git config --global user.name "Antonio Kobashikawa"
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/akobashikawa/curso-elementos-desarrollo-web.git

    - name: Build and Deploy
      run: |
        npm ci
        npm run build2
        git add -f src/.vuepress/dist && git commit -m "Updated dist"
        git subtree push --prefix src/.vuepress/dist origin gh-pages
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        VUEPRESS_BASE: "/curso-elementos-desarrollo-web/"
